language: ruby
cache: bundler
rvm:
  - 2.2.3
addons:
  postgresql: '9.3'
  code_climate:
    repo_token: d11376230ce9172f8825ebcd9253fa90e44f46b6f5e9a1f2a121576f2d4bf729
services:
  - postgresql
before_script:
  - cp config/database.yml.travis config/database.yml
  - cp .env.example .env
  - psql -c 'create database travis_ci_test;' -U postgres
  - bundle exec rake db:setup AUTO_ACCEPT=true
script:
  - bundle exec rspec -f d
