default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: twitter_api_challenge_development

test:
  <<: *default
  database: twitter_api_challenge_test

production:
  <<: *default
  database: twitter_api_challenge
